Update CI build scripts to exclude Expecta

diff --git a/Support/Scripts/objc-build-scripts/cibuild b/Support/Scripts/objc-build-scripts/cibuild
--- a/Support/Scripts/objc-build-scripts/cibuild
+++ b/Support/Scripts/objc-build-scripts/cibuild
@@ -40,12 +40,16 @@ config ()
     #
     # Individual names can be quoted to avoid word splitting.
     : ${SCHEMES:=$(xcodebuild -list -project "$XCODEPROJ" 2>/dev/null | awk -f "$SCRIPT_DIR/schemes.awk")}
-    
+
+    # A whitespace-separated list of executables that must be present and locatable.
+    : ${REQUIRED_TOOLS="xctool"}
+
     export XCWORKSPACE
     export XCODEPROJ
     export BOOTSTRAP
     export XCTOOL_OPTIONS
     export SCHEMES
+    export REQUIRED_TOOLS
 }
 
 ##
@@ -55,6 +59,12 @@ config ()
 main ()
 {
     config
+
+    if [ -n "$REQUIRED_TOOLS" ]
+    then
+        echo "*** Checking dependencies..."
+        check_deps
+    fi
 
     if [ -f "$BOOTSTRAP" ]
     then
@@ -76,6 +86,19 @@ main ()
 
         exit $status
     )
+}
+
+check_deps ()
+{
+    for tool in $REQUIRED_TOOLS
+    do
+        which -s "$tool"
+        if [ "$?" -ne "0" ]
+        then
+            echo "*** Error: $tool not found. Please install it and cibuild again."
+            exit 1
+        fi
+    done
 }
 
 find_pattern ()
@@ -106,9 +129,6 @@ build_scheme ()
 {
     local scheme=$1
 
-    echo "*** Cleaning $scheme..."
-    run_xctool -scheme "$scheme" clean >/dev/null || exit $?
-
     echo "*** Building and testing $scheme..."
     echo
 
@@ -120,16 +140,27 @@ build_scheme ()
 
     local awkstatus=$?
 
+    if [ "$awkstatus" -eq "1" ]
+    then
+        # SDK not found, try for iphonesimulator.
+        sdkflag="-sdk iphonesimulator"
+
+        # Determine whether the unit tests will run with iphonesimulator
+        run_xctool $sdkflag -scheme "$scheme" run-tests | parse_build
+
+        awkstatus=$?
+
+        if [ "$awkstatus" -ne "0" ]
+        then
+            # Unit tests will not run on iphonesimulator.
+            sdkflag=""
+        fi
+    fi
+
     if [ "$awkstatus" -ne "0" ]
     then
         # Unit tests aren't supported.
         action=build
-    fi
-
-    if [ "$awkstatus" -eq "1" ]
-    then
-        # Build for iOS.
-        sdkflag="-sdk iphonesimulator"
     fi
 
     run_xctool $sdkflag -scheme "$scheme" $action
